# 1. 模型定义
model_filename: 'deeplabv3_plus_model'
model_classname: 'DeepLabV3Plus'


model_args:
  n_channels: 3
  n_classes: 1
  backbone: 'resnet101'
  output_stride: 16
  pretrained: true

# 2. 前向传播额外参数
# forward_args:

# 3. 训练超参数
random_seed: 6
epochs: 200
batch_size: 8
learning_rate: 0.0002
weight_decay: 0.0001
amp: true
load: null
warm_up_step: 100
max_norm: 1.0

# 学习率调度器配置
scheduler:
  # 'ReduceLROnPlateau' 或 'CosineAnnealingLR'
  active_scheduler: 'CosineAnnealingLR'

  # ReduceLROnPlateau 的参数块
  ReduceLROnPlateau_params:
    factor: 0.2
    patience: 5
    min_lr: 1.0e-6
    mode: 'max'
    verbose: true

  # CosineAnnealingLR 的参数块
  CosineAnnealingLR_params:
    T_max: 200
    eta_min: 1.0e-6

# 4. 数据集参数
dataset_name: ''
root_dir: ''
image_size: 1024

# 5. 评估与保存
evaluate_epoch: 1
evaluate_inteval: 1
save_checkpoint: true
save_interval: 50
save_best_model: true

# 6. 日志参数
log_project_name: ''

# 7. 推理阶段配置
inference:
  model_path: ''
  threshold: 0.5
  save_outputs: true
  save_binary_mask: true
  save_prob_map: false
  save_error_map: true

tta:
  enable: false
  ops:
    - 'identity'
    - 'hflip'
    - 'vflip'

# 8. Comet.ml 在线日志 API
comet_ml:
  api_key: ''
  project_name: ''
