# 1. 模型定义
model_filename: 'rs_mamba_ss_model'
model_classname: 'RSM_SS'

model_args:
  in_chans: 3
  num_classes: 1
  dims: [96, 192, 384, 768]
  depths: [2, 2, 9, 2]
  drop_path_rate: 0.2


# 2. 前向传播额外参数 (可选)
# RS_Mamba_SS_Model 的 forward 函数只有一个输入x，因此此项为空
# forward_args:

# 3. 训练超参数
random_seed: 6
epochs: 150
batch_size: 8
learning_rate: 0.0002
weight_decay: 0.0001
amp: true
load: null
warm_up_step: 100
max_norm: 1.0

# 学习率调度器配置
scheduler:
  active_scheduler: 'CosineAnnealingLR'

  ReduceLROnPlateau_params:
    factor: 0.1
    patience: 12
    min_lr: 1.0e-6
    mode: 'max'
    verbose: true

  CosineAnnealingLR_params:
    T_max: 150
    eta_min: 1.0e-6

# 4. 数据集参数
dataset_name: ''
root_dir: ''
image_size: 1024

# 5. 评估与保存
evaluate_epoch: 1
evaluate_inteval: 1
save_checkpoint: true
save_interval: 50
save_best_model: true

# 6. 日志参数
log_project_name: ''

# 7. 推理阶段配置
inference:
  model_path: ''
  threshold: 0.5
  save_outputs: true
  save_binary_mask: true
  save_prob_map: false
  save_error_map: true

tta:
  enable: false
  ops:
    - 'identity'
    - 'hflip'

# 8. Comet.ml 在线日志 API
comet_ml:
  api_key: ''
  project_name: ''
