model_filename: 'unet_model'
model_classname: 'UNet'

model_args:
  n_channels: 3
  n_classes: 1
  bilinear: False

random_seed: 6
epochs: 200
batch_size: 2
learning_rate: 0.0002
weight_decay: 0.0001
amp: true
load: null
warm_up_step: 100
max_norm: 1.0

scheduler:
  active_scheduler: 'CosineAnnealingLR'

  # ReduceLROnPlateau 的参数块
  ReduceLROnPlateau_params:
    factor: 0.2
    patience: 5
    min_lr: 1.0e-6
    mode: 'max'
    verbose: true

  # CosineAnnealingLR 的参数块
  CosineAnnealingLR_params:
    T_max: 200
    eta_min: 1.0e-6

dataset_name: ''
root_dir: ''
image_size: 1024

evaluate_epoch: 1
evaluate_inteval: 1
save_checkpoint: true
save_interval: 50
save_best_model: true

log_project_name: ''


# 7. 推理阶段配置
# ----------------------------------------------------------------
inference:
  model_path: 'null'
  threshold: 0.5
  save_outputs: false
  save_binary_mask: true
  save_prob_map: false
  save_error_map: false

tta:
  enable: false
  ops:
    - 'identity'
    - 'hflip'
    - 'vflip'
    - 'rot90'

comet_ml:
  api_key: ''
  project_name: ''
